### ISSUE TITLE
Conversational AI Example Bug - AudioContext Construction Failure

### ISSUE THREAD

**Issue by araaday** [elevenlabs/elevenlabs-examples#123]
Encountered an issue when following the JavaScript example provided for conversational AI. The app fails to start a connect to Elevenlabs and throws an error related to the AudioContext construction.

**Steps to Reproduce**

1. Follow the JavaScript example provided for conversational AI.
2. Attempt to start a conversation using the provided code.
3. Observe the error in the console.

`bundle.js:1 Error starting conversation: TypeError: Failed to construct 'AudioContext': Failed to read the 'sampleRate' property from 'AudioContextOptions': The provided float value is non-finite.
    at c.create (bundle.js:1:6019)
    at p.startSession (bundle.js:1:8357)
    at async HTMLButtonElement.<anonymous> (bundle.js:1:14599)
`

**Comment by louisjoecodes** [comment]
Hi there! Sorry you experienced this - which sampleRate is your agent currently configured to use?

**Comment by Charles-de-Montigny** [comment]
I got the exact same error. When I console log the value of the sample rate it is set to 16000 which is supposed to be a valid value.

**Comment by ritzy1978** [comment]
The only codec that I could get working was "u-law 8000hz". All the others, I just get static.

**Comment by thorwebdev** [comment]
Just tested with `PCM 16000 Hz` setting and the `conversational-ai/javascript` and it's working fine for me. Closing this out, but please reopen with additional browser and system information should you still be experiencing this issue. Thanks!
