### ISSUE TITLE
@elevenlabs-alpha/react

### ISSUE THREAD

**Issue by tweetsydotio** [elevenlabs/elevenlabs-examples#124]
yarn
yarn install v1.22.22
[1/4] Resolving packages...
error Error: https://registry.yarnpkg.com/@elevenlabs-alpha%2freact: Not found
    at params.callback [as _callback] (/home/taher/.nvm/versions/node/v20.18.0/lib/node_modules/yarn/lib/cli.js:66680:18)
    at self.callback (/home/taher/.nvm/versions/node/v20.18.0/lib/node_modules/yarn/lib/cli.js:141410:22)
    at Request.emit (node:events:519:28)
    at Request.<anonymous> (/home/taher/.nvm/versions/node/v20.18.0/lib/node_modules/yarn/lib/cli.js:142382:10)
    at Request.emit (node:events:519:28)
    at IncomingMessage.<anonymous> (/home/taher/.nvm/versions/node/v20.18.0/lib/node_modules/yarn/lib/cli.js:142304:12)
    at Object.onceWrapper (node:events:633:28)
    at IncomingMessage.emit (node:events:531:35)
    at endReadableNT (node:internal/streams/readable:1696:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:82:21)
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.

**Comment by louisjoecodes** [comment]
Hi there - we don't have an @elevenlabs-alpha/react package?
