### ISSUE TITLE
dubbing

### ISSUE THREAD

**Issue by wanglongpeng1** [elevenlabs/elevenlabs-examples#44]
"download_dubbed_file" function error

Dubbing in progress... Will check status again in 10 seconds.
Dubbing in progress... Will check status again in 10 seconds.
Traceback (most recent call last):
  File "/datahdd/wyz/wlp/11LABS_Dubbings/examples/create_a_dub_from_file.py", line 65, in <module>
    result = create_dub_from_file(
             ^^^^^^^^^^^^^^^^^^^^^
  File "/datahdd/wyz/wlp/11LABS_Dubbings/examples/create_a_dub_from_file.py", line 58, in create_dub_from_file
    output_file_path = download_dubbed_file(dubbing_id, target_language)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/datahdd/wyz/wlp/11LABS_Dubbings/examples/dubbing_utils.py", line 39, in download_dubbed_file
    for chunk in client.dubbing.get_dubbed_file(dubbing_id, language_code):
TypeError: 'NoneType' object is not iterable

The video that has been dubbed cannot be downloaded to the local, and the return is empty. But after I log in to my account on the official website, I can see the file in the history.
After investigating for a long time, I can't find the reason.
已经dubbing后的视频 无法下载到本地，返回的是空，我上官方网站登陆账号后可以在历史中看到文件，排查了很久找不到原因。

**Comment by thorwebdev** [comment]
Closing this out as stale. Please reopen if you're still experiencing this issue! Thanks.
